# LLM Provider Configuration
# Choose which provider to use: gemini, deepseek, huggingface, qwen, openai
llm_provider: gemini

# Provider-specific configurations
providers:
  # Google Gemini Configuration
  gemini:
    api_key: "AIzaSyDxuh2N0WbNHlui66ZftNPBH9G3n1vqZ00"
    model: "gemini-2.0-flash"
    # Alternative models: "gemini-1.5-pro", "gemini-1.5-flash"
  
  # DeepSeek Configuration
  deepseek:
    api_key: "sk-a58dd7f5d004490986ec32c78796421b"
    model: "deepseek-ai/DeepSeek-V2.5-1210"
    # Alternative models: "deepseek-coder"
  
  # Hugging Face Configuration (runs locally)
  huggingface:
    model: "microsoft/DialoGPT-large"
    # Alternative models: 
    # - "microsoft/DialoGPT-medium"
    # - "microsoft/DialoGPT-small"
    # - "gpt2"
    # - "EleutherAI/gpt-neo-2.7B"
    # - "microsoft/phi-2"
  
  # Qwen Configuration (Alibaba Cloud)
  qwen:
    api_key: "your-qwen-api-key-here"
    model: "qwen-turbo"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    # Alternative models: 
    # - "qwen-plus"
    # - "qwen-max"
    # - "qwen-max-longcontext"
  
  # OpenAI Configuration
  openai:
    api_key: "your-openai-api-key-here"
    model: "gpt-3.5-turbo"
    # Alternative models:
    # - "gpt-4"
    # - "gpt-4-turbo"
    # - "gpt-4o"
    # - "gpt-4o-mini"

# Optional: Global settings
settings:
  temperature: 0.1
  max_tokens: 5000
  timeout: 30